smax-postgres: src/smax-postgres.c File Reference
smax-postgres.c File Reference
Functions
int main (int argc, const char *argv[])
Variables
boolean debug = FALSE
whether to show debug messages
Detailed Description
Date
Created on Nov 5, 2023
Author
Attila Kovacs
Logging of SMA-X variables to a historical database, such as an SQL database. Cofiguration of the logger is possible via a designated configuration file, which can be specified at runtime via the -c option.
Function Documentation
main()
int main (int argc, const char * argv[])
Main entry point of the smax-postgress SMA-X to PostgreSQL / TimescaleDB connector application
Parameters
argc Number of command-line arguments passed
argv An array of command-line argument strings
Returns
0 id the program exited normally, or else a non-zero exit code.
References debug, ERROR_EXIT, FALSE, initCollector(), parseConfig(), setupDB(), SMAXPQ_DEFAULT_CONFIG, SMAXPQ_VERSION_STRING, SQLThread(), and SUCCESS_RETURN.